//
//  CartItemListViewController.swift
//  Capsula
//
//  Created SherifShokry on 3/29/20.
//  Copyright © 2020 SherifShokry. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class CartItemListViewController: UIViewController {
    
    var presenter : ViewToPresenterCartItemListProtocol?

    
    override func viewDidLoad() {
        super.viewDidLoad()
       
    }
    
    
}
extension CartItemListViewController : PresenterToViewCartItemListProtocol {
    

}
