//
//  CartItemListProtocols.swift
//  Capsula
//
//  Created SherifShokry on 3/29/20.
//  Copyright © 2020 SherifShokry. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation


protocol ViewToPresenterCartItemListProtocol: class {
    
    var view : PresenterToViewCartItemListProtocol? {get set}
    var interactor : PresenterToIntetractorCartItemListProtocol? {get set}
    var router : PresenterToRouterCartItemListProtocol? {get set}
}

protocol PresenterToViewCartItemListProtocol: class {
  
}

protocol PresenterToIntetractorCartItemListProtocol: class {
    var presenter: InteractorToPresenterCartItemListProtocol? { get set }
    
}

protocol PresenterToRouterCartItemListProtocol: class  {
    static func createModule() -> UIViewController
    
}

protocol InteractorToPresenterCartItemListProtocol: class {
   
}
