//
//  CartItemListPresenter.swift
//  Capsula
//
//  Created SherifShokry on 3/29/20.
//  Copyright © 2020 SherifShokry. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

class CartItemListPresenter : ViewToPresenterCartItemListProtocol{
    
    var view: PresenterToViewCartItemListProtocol?
    var interactor: PresenterToIntetractorCartItemListProtocol?
    var router: PresenterToRouterCartItemListProtocol?
    
}

extension CartItemListPresenter : InteractorToPresenterCartItemListProtocol {
    
 
}

