//
//  ItemsListPresenter.swift
//  Capsula
//
//  Created SherifShokry on 2/15/20.
//  Copyright © 2020 SherifShokry. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

class ItemsListPresenter : ViewToPresenterItemsListProtocol{
    
    var view: PresenterToViewItemsListProtocol?
    var interactor: PresenterToIntetractorItemsListProtocol?
    var router: PresenterToRouterItemsListProtocol?
    
}

extension ItemsListPresenter : InteractorToPresenterItemsListProtocol {
    
 
}

