//
//  ItemsListProtocols.swift
//  Capsula
//
//  Created SherifShokry on 2/15/20.
//  Copyright © 2020 SherifShokry. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation


protocol ViewToPresenterItemsListProtocol: class {
    
    var view : PresenterToViewItemsListProtocol? {get set}
    var interactor : PresenterToIntetractorItemsListProtocol? {get set}
    var router : PresenterToRouterItemsListProtocol? {get set}
}

protocol PresenterToViewItemsListProtocol: class {
  
}

protocol PresenterToIntetractorItemsListProtocol: class {
    var presenter: InteractorToPresenterItemsListProtocol? { get set }
    
}

protocol PresenterToRouterItemsListProtocol: class  {
    static func createModule() -> UIViewController
    
}

protocol InteractorToPresenterItemsListProtocol: class {
   
}
