//
//  ItemsListRouter.swift
//  Capsula
//
//  Created SherifShokry on 2/15/20.
//  Copyright © 2020 SherifShokry. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit


    class ItemsListRouter : PresenterToRouterItemsListProtocol {
        
        static func createModule() -> UIViewController {
            
            let view = ItemsListViewController.instantiateFromStoryBoard(appStoryBoard: /*replace with storyboard name*/)
            let presenter : ViewToPresenterItemsListProtocol & InteractorToPresenterItemsListProtocol = ItemsListPresenter()
            let interactor : PresenterToIntetractorItemsListProtocol = ItemsListInteractor()
            let router : PresenterToRouterItemsListProtocol = ItemsListRouter()
            
            view.presenter = presenter
            presenter.interactor = interactor
            presenter.view = view
            presenter.router = router
            interactor.presenter = presenter
            return view
        }
    }
