//
//  ItemsListInteractor.swift
//  Capsula
//
//  Created SherifShokry on 2/15/20.
//  Copyright © 2020 SherifShokry. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class ItemsListInteractor : PresenterToIntetractorItemsListProtocol {
    
    var presenter: InteractorToPresenterItemsListProtocol?
    
}

