//
//  CartDetailsProtocols.swift
//  Capsula
//
//  Created SherifShokry on 4/3/20.
//  Copyright © 2020 SherifShokry. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation


protocol ViewToPresenterCartDetailsProtocol: class {
    
    var view : PresenterToViewCartDetailsProtocol? {get set}
    var interactor : PresenterToIntetractorCartDetailsProtocol? {get set}
    var router : PresenterToRouterCartDetailsProtocol? {get set}
}

protocol PresenterToViewCartDetailsProtocol: class {
  
}

protocol PresenterToIntetractorCartDetailsProtocol: class {
    var presenter: InteractorToPresenterCartDetailsProtocol? { get set }
    
}

protocol PresenterToRouterCartDetailsProtocol: class  {
    static func createModule() -> UIViewController
    
}

protocol InteractorToPresenterCartDetailsProtocol: class {
   
}
