//
//  CartDetailsViewController.swift
//  Capsula
//
//  Created SherifShokry on 4/3/20.
//  Copyright © 2020 SherifShokry. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class CartDetailsViewController: UIViewController {
    
    var presenter : ViewToPresenterCartDetailsProtocol?

    
    override func viewDidLoad() {
        super.viewDidLoad()
       
    }
    
    
}
extension CartDetailsViewController : PresenterToViewCartDetailsProtocol {
    

}
