//
//  CartDetailsInteractor.swift
//  Capsula
//
//  Created SherifShokry on 4/3/20.
//  Copyright © 2020 SherifShokry. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class CartDetailsInteractor : PresenterToIntetractorCartDetailsProtocol {
    
    var presenter: InteractorToPresenterCartDetailsProtocol?
    
}

