//
//  CartDetailsPresenter.swift
//  Capsula
//
//  Created SherifShokry on 4/3/20.
//  Copyright © 2020 SherifShokry. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

class CartDetailsPresenter : ViewToPresenterCartDetailsProtocol{
    func setPaymentMethod(method: Int) {
        
    }
    
  
    func getDevliveryCost() {
        self.view?.changeState(state: .loading)
        self.interactor?.getDeliveryCost()
    }
    
   
    
    func prepareCheckout(){
         self.view?.changeState(state: .loading)
        //5 for madda payment
         self.interactor?.prepareCheckout(paymentMethodID: 5)
    }
    
    var view: PresenterToViewCartDetailsProtocol?
    var interactor: PresenterToIntetractorCartDetailsProtocol?
    var router: PresenterToRouterCartDetailsProtocol?
    var checkoutRequest = CheckoutRequest()
    
    func checkout() {
        self.view?.changeState(state: .loading)
        self.interactor?.checkout(request: checkoutRequest)
     }
     
     func setPreprictionImage(image: String) {
        
        checkoutRequest.prescriptionImage  = image
     }
     
     func setInsuranceImage(image: String) {
        
        checkoutRequest.insuranceNumberImage = image
     }
     
    
     
    
    
    
}

extension CartDetailsPresenter : InteractorToPresenterCartDetailsProtocol {
    func checkoutIDFetchedSuccessfully(checkoutID: String) {
        self.view?.changeState(state: .ready)
        print(checkoutID)
        //Open Madda SDK to Complete payment
    }
    
    func deliveryCostFetchedSuccessfully(deliveryCost: String) {
          self.view?.changeState(state: .ready)
          self.view?.setDeliveryCost(cost: deliveryCost)
    }
    
    func checkoutDoneSuccessfully() {
        Utils.emptyLocalCart()
        self.view?.changeState(state: .ready)
        self.view?.moveToSuccessScreen()
    }
    
    func checkoutFailed(error: String) {
        self.view?.changeState(state: .error(error))
    }
    
    
 
}

