//
//  CartDetailsPresenter.swift
//  Capsula
//
//  Created SherifShokry on 4/3/20.
//  Copyright © 2020 SherifShokry. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

class CartDetailsPresenter : ViewToPresenterCartDetailsProtocol{
    
    var view: PresenterToViewCartDetailsProtocol?
    var interactor: PresenterToIntetractorCartDetailsProtocol?
    var router: PresenterToRouterCartDetailsProtocol?
    
}

extension CartDetailsPresenter : InteractorToPresenterCartDetailsProtocol {
    
 
}

