//
//  SubCategoriesListPresenter.swift
//  Capsula
//
//  Created SherifShokry on 2/8/20.
//  Copyright © 2020 SherifShokry. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

class SubCategoriesListPresenter : ViewToPresenterSubCategoriesListProtocol{
    
    var view: PresenterToViewSubCategoriesListProtocol?
    var interactor: PresenterToIntetractorSubCategoriesListProtocol?
    var router: PresenterToRouterSubCategoriesListProtocol?
    
}

extension SubCategoriesListPresenter : InteractorToPresenterSubCategoriesListProtocol {
    
 
}

