//
//  SubCategoriesListProtocols.swift
//  Capsula
//
//  Created SherifShokry on 2/8/20.
//  Copyright © 2020 SherifShokry. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation


protocol ViewToPresenterSubCategoriesListProtocol: class {
    
    var view : PresenterToViewSubCategoriesListProtocol? {get set}
    var interactor : PresenterToIntetractorSubCategoriesListProtocol? {get set}
    var router : PresenterToRouterSubCategoriesListProtocol? {get set}
}

protocol PresenterToViewSubCategoriesListProtocol: class {
  
}

protocol PresenterToIntetractorSubCategoriesListProtocol: class {
    var presenter: InteractorToPresenterSubCategoriesListProtocol? { get set }
    
}

protocol PresenterToRouterSubCategoriesListProtocol: class  {
    static func createModule() -> UIViewController
    
}

protocol InteractorToPresenterSubCategoriesListProtocol: class {
   
}
