//
//  SubCategoriesListInteractor.swift
//  Capsula
//
//  Created SherifShokry on 2/8/20.
//  Copyright © 2020 SherifShokry. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class SubCategoriesListInteractor : PresenterToIntetractorSubCategoriesListProtocol {
    
    var presenter: InteractorToPresenterSubCategoriesListProtocol?
    
}

