//
//  SubCategoriesListRouter.swift
//  Capsula
//
//  Created SherifShokry on 2/8/20.
//  Copyright © 2020 SherifShokry. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit


    class SubCategoriesListRouter : PresenterToRouterSubCategoriesListProtocol {
        
        static func createModule() -> UIViewController {
            
            let view = SubCategoriesListViewController.instantiateFromStoryBoard(appStoryBoard: /*replace with storyboard name*/)
            let presenter : ViewToPresenterSubCategoriesListProtocol & InteractorToPresenterSubCategoriesListProtocol = SubCategoriesListPresenter()
            let interactor : PresenterToIntetractorSubCategoriesListProtocol = SubCategoriesListInteractor()
            let router : PresenterToRouterSubCategoriesListProtocol = SubCategoriesListRouter()
            
            view.presenter = presenter
            presenter.interactor = interactor
            presenter.view = view
            presenter.router = router
            interactor.presenter = presenter
            return view
        }
    }
