//
//  MainCartViewController.swift
//  Capsula
//
//  Created SherifShokry on 3/29/20.
//  Copyright © 2020 SherifShokry. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class MainCartViewController: UIViewController {
    
    var presenter : ViewToPresenterMainCartProtocol?

    
    override func viewDidLoad() {
        super.viewDidLoad()
       
    }
    
    
}
extension MainCartViewController : PresenterToViewMainCartProtocol {
    

}
