//
//  SearchItemRouter.swift
//  Capsula
//
//  Created SherifShokry on 2/24/20.
//  Copyright © 2020 SherifShokry. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit


    class SearchItemRouter : PresenterToRouterSearchItemProtocol {
        
        static func createModule() -> UIViewController {
            
            let view = SearchItemViewController.instantiateFromStoryBoard(appStoryBoard: /*replace with storyboard name*/)
            let presenter : ViewToPresenterSearchItemProtocol & InteractorToPresenterSearchItemProtocol = SearchItemPresenter()
            let interactor : PresenterToIntetractorSearchItemProtocol = SearchItemInteractor()
            let router : PresenterToRouterSearchItemProtocol = SearchItemRouter()
            
            view.presenter = presenter
            presenter.interactor = interactor
            presenter.view = view
            presenter.router = router
            interactor.presenter = presenter
            return view
        }
    }
