//
//  SearchItemViewController.swift
//  Capsula
//
//  Created SherifShokry on 2/24/20.
//  Copyright © 2020 SherifShokry. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class SearchItemViewController: UIViewController {
    
    var presenter : ViewToPresenterSearchItemProtocol?

    
    override func viewDidLoad() {
        super.viewDidLoad()
       
    }
    
    
}
extension SearchItemViewController : PresenterToViewSearchItemProtocol {
    

}
