//
//  SearchItemPresenter.swift
//  Capsula
//
//  Created SherifShokry on 2/24/20.
//  Copyright © 2020 SherifShokry. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

class SearchItemPresenter : ViewToPresenterSearchItemProtocol{
    
    var view: PresenterToViewSearchItemProtocol?
    var interactor: PresenterToIntetractorSearchItemProtocol?
    var router: PresenterToRouterSearchItemProtocol?
    
}

extension SearchItemPresenter : InteractorToPresenterSearchItemProtocol {
    
 
}

