//
//  SearchItemProtocols.swift
//  Capsula
//
//  Created SherifShokry on 2/24/20.
//  Copyright © 2020 SherifShokry. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation


protocol ViewToPresenterSearchItemProtocol: class {
    
    var view : PresenterToViewSearchItemProtocol? {get set}
    var interactor : PresenterToIntetractorSearchItemProtocol? {get set}
    var router : PresenterToRouterSearchItemProtocol? {get set}
}

protocol PresenterToViewSearchItemProtocol: class {
  
}

protocol PresenterToIntetractorSearchItemProtocol: class {
    var presenter: InteractorToPresenterSearchItemProtocol? { get set }
    
}

protocol PresenterToRouterSearchItemProtocol: class  {
    static func createModule() -> UIViewController
    
}

protocol InteractorToPresenterSearchItemProtocol: class {
   
}
