//
//  MainHomeInteractor.swift
//  Capsula
//
//  Created SherifShokry on 2/2/20.
//  Copyright © 2020 SherifShokry. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class MainHomeInteractor : PresenterToIntetractorMainHomeProtocol {
    
    var presenter: InteractorToPresenterMainHomeProtocol?
    
}

