//
//  MainHomeProtocols.swift
//  Capsula
//
//  Created SherifShokry on 2/2/20.
//  Copyright © 2020 SherifShokry. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation


protocol ViewToPresenterMainHomeProtocol: class {
    
    var view : PresenterToViewMainHomeProtocol? {get set}
    var interactor : PresenterToIntetractorMainHomeProtocol? {get set}
    var router : PresenterToRouterMainHomeProtocol? {get set}
}

protocol PresenterToViewMainHomeProtocol: class {
  
}

protocol PresenterToIntetractorMainHomeProtocol: class {
    var presenter: InteractorToPresenterMainHomeProtocol? { get set }
    
}

protocol PresenterToRouterMainHomeProtocol: class  {
    static func createModule() -> UIViewController
    
}

protocol InteractorToPresenterMainHomeProtocol: class {
   
}
