//
//  MainHomePresenter.swift
//  Capsula
//
//  Created SherifShokry on 2/2/20.
//  Copyright © 2020 SherifShokry. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

class MainHomePresenter : ViewToPresenterMainHomeProtocol{
    
    var view: PresenterToViewMainHomeProtocol?
    var interactor: PresenterToIntetractorMainHomeProtocol?
    var router: PresenterToRouterMainHomeProtocol?
    
}

extension MainHomePresenter : InteractorToPresenterMainHomeProtocol {
    
 
}

