//
//  MainHomePresenter.swift
//  Capsula
//
//  Created SherifShokry on 2/2/20.
//  Copyright © 2020 SherifShokry. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//
import Foundation

class MainHomePresenter : ViewToPresenterMainHomeProtocol{
 
  
    var view: PresenterToViewMainHomeProtocol?
    var interactor: PresenterToIntetractorMainHomeProtocol?
    var router: PresenterToRouterMainHomeProtocol?
    var storesData : [Store] = []
    
    func  getStoresData() {
        self.view?.changeState(state: .loading)
        self.interactor?.getStoresData()
        
        if Utils.loadUser()?.accessToken ?? "" != "" {
            self.interactor?.updateUserData()
        }
        
      }
    
    
    var numberOfRows : Int {
        return storesData.count
    }
    
    func configureStoreCell(cell: StoreCell, indexPath: IndexPath) {
        cell.setStoreData(store: storesData[indexPath.item])
    }
    
    
    func didSelectStore(indexPath: IndexPath) {
           self.router?.openCategoriesScreen(from: self.view, storeId: storesData[indexPath.item].storeId ?? -1 )
       }
    
 
    
}
extension MainHomePresenter : InteractorToPresenterMainHomeProtocol {
 
    func storesDataFetchedSuccessfully(storesResponse: [Store]) {
        self.storesData = storesResponse
        self.view?.changeState(state: .ready)
    }
    
    func storesDataFailedToFetch(error: String) {
        self.view?.changeState(state: .error(error))
    }
    
    
    func homeDataFailedToFetch(error: String) {
        self.view?.changeState(state: .error(error))
    }

}
