//
//  MainHomeRouter.swift
//  Capsula
//
//  Created SherifShokry on 2/2/20.
//  Copyright © 2020 SherifShokry. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit


    class MainHomeRouter : PresenterToRouterMainHomeProtocol {
        
        static func createModule() -> UIViewController {
            
            let view = MainHomeViewController.instantiateFromStoryBoard(appStoryBoard: /*replace with storyboard name*/)
            let presenter : ViewToPresenterMainHomeProtocol & InteractorToPresenterMainHomeProtocol = MainHomePresenter()
            let interactor : PresenterToIntetractorMainHomeProtocol = MainHomeInteractor()
            let router : PresenterToRouterMainHomeProtocol = MainHomeRouter()
            
            view.presenter = presenter
            presenter.interactor = interactor
            presenter.view = view
            presenter.router = router
            interactor.presenter = presenter
            return view
        }
    }
