//
//  SideMenuPresenter.swift
//  Capsula
//
//  Created SherifShokry on 2/15/20.
//  Copyright © 2020 SherifShokry. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

class SideMenuPresenter : ViewToPresenterSideMenuProtocol{
    
    var view: PresenterToViewSideMenuProtocol?
    var interactor: PresenterToIntetractorSideMenuProtocol?
    var router: PresenterToRouterSideMenuProtocol?
    
}

extension SideMenuPresenter : InteractorToPresenterSideMenuProtocol {
    
 
}

