//
//  SideMenuProtocols.swift
//  Capsula
//
//  Created SherifShokry on 2/15/20.
//  Copyright © 2020 SherifShokry. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation


protocol ViewToPresenterSideMenuProtocol: class {
    
    var view : PresenterToViewSideMenuProtocol? {get set}
    var interactor : PresenterToIntetractorSideMenuProtocol? {get set}
    var router : PresenterToRouterSideMenuProtocol? {get set}
}

protocol PresenterToViewSideMenuProtocol: class {
  
}

protocol PresenterToIntetractorSideMenuProtocol: class {
    var presenter: InteractorToPresenterSideMenuProtocol? { get set }
    
}

protocol PresenterToRouterSideMenuProtocol: class  {
    static func createModule() -> UIViewController
    
}

protocol InteractorToPresenterSideMenuProtocol: class {
   
}
