//
//  SideMenuRouter.swift
//  Capsula
//
//  Created SherifShokry on 2/15/20.
//  Copyright © 2020 SherifShokry. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit


    class SideMenuRouter : PresenterToRouterSideMenuProtocol {
        
        static func createModule() -> UIViewController {
            
            let view = SideMenuViewController.instantiateFromStoryBoard(appStoryBoard: /*replace with storyboard name*/)
            let presenter : ViewToPresenterSideMenuProtocol & InteractorToPresenterSideMenuProtocol = SideMenuPresenter()
            let interactor : PresenterToIntetractorSideMenuProtocol = SideMenuInteractor()
            let router : PresenterToRouterSideMenuProtocol = SideMenuRouter()
            
            view.presenter = presenter
            presenter.interactor = interactor
            presenter.view = view
            presenter.router = router
            interactor.presenter = presenter
            return view
        }
    }
