//
//  BrandsListViewController.swift
//  Capsula
//
//  Created SherifShokry on 2/15/20.
//  Copyright © 2020 SherifShokry. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class BrandsListViewController: UIViewController {
    
    var presenter : ViewToPresenterBrandsListProtocol?

    
    override func viewDidLoad() {
        super.viewDidLoad()
       
    }
    
    
}
extension BrandsListViewController : PresenterToViewBrandsListProtocol {
    

}
