//
//  BrandsListProtocols.swift
//  Capsula
//
//  Created SherifShokry on 2/15/20.
//  Copyright © 2020 SherifShokry. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation


protocol ViewToPresenterBrandsListProtocol: class {
    
    var view : PresenterToViewBrandsListProtocol? {get set}
    var interactor : PresenterToIntetractorBrandsListProtocol? {get set}
    var router : PresenterToRouterBrandsListProtocol? {get set}
}

protocol PresenterToViewBrandsListProtocol: class {
  
}

protocol PresenterToIntetractorBrandsListProtocol: class {
    var presenter: InteractorToPresenterBrandsListProtocol? { get set }
    
}

protocol PresenterToRouterBrandsListProtocol: class  {
    static func createModule() -> UIViewController
    
}

protocol InteractorToPresenterBrandsListProtocol: class {
   
}
