//
//  BrandsListRouter.swift
//  Capsula
//
//  Created SherifShokry on 2/15/20.
//  Copyright © 2020 SherifShokry. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit


    class BrandsListRouter : PresenterToRouterBrandsListProtocol {
        
        static func createModule() -> UIViewController {
            
            let view = BrandsListViewController.instantiateFromStoryBoard(appStoryBoard: /*replace with storyboard name*/)
            let presenter : ViewToPresenterBrandsListProtocol & InteractorToPresenterBrandsListProtocol = BrandsListPresenter()
            let interactor : PresenterToIntetractorBrandsListProtocol = BrandsListInteractor()
            let router : PresenterToRouterBrandsListProtocol = BrandsListRouter()
            
            view.presenter = presenter
            presenter.interactor = interactor
            presenter.view = view
            presenter.router = router
            interactor.presenter = presenter
            return view
        }
    }
