//
//  BrandsListPresenter.swift
//  Capsula
//
//  Created SherifShokry on 2/15/20.
//  Copyright © 2020 SherifShokry. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

class BrandsListPresenter : ViewToPresenterBrandsListProtocol{
    
    var view: PresenterToViewBrandsListProtocol?
    var interactor: PresenterToIntetractorBrandsListProtocol?
    var router: PresenterToRouterBrandsListProtocol?
    
}

extension BrandsListPresenter : InteractorToPresenterBrandsListProtocol {
    
 
}

