//
//  ResetPasswordPresenter.swift
//  Capsula
//
//  Created SherifShokry on 1/4/20.
//  Copyright © 2020 SherifShokry. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

class ResetPasswordPresenter : ViewToPresenterResetPasswordProtocol{
    
    var view: PresenterToViewResetPasswordProtocol?
    var interactor: PresenterToIntetractorResetPasswordProtocol?
    var router: PresenterToRouterResetPasswordProtocol?
    var phone = ""
       
    func resetPassword(password : String) {
           self.view?.changeState(state: .loading)
           self.interactor?.resetPassword(phone: phone, password: password)
       }
}

extension ResetPasswordPresenter : InteractorToPresenterResetPasswordProtocol {
      func passwordUpdatedSuccessfully() {
           self.view?.changeState(state: .ready)
           self.view?.showSuccessMsg(msg: Strings.resetPasswordSuccessMsg)
       }
       
       func passwordFailedToUpdate(error: String) {
           self.view?.changeState(state: .error(error))
       }
 
}

