//
//  ResetPasswordPresenter.swift
//  Capsula
//
//  Created SherifShokry on 1/4/20.
//  Copyright © 2020 SherifShokry. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

class ResetPasswordPresenter : ViewToPresenterResetPasswordProtocol{
    
    var view: PresenterToViewResetPasswordProtocol?
    var interactor: PresenterToIntetractorResetPasswordProtocol?
    var router: PresenterToRouterResetPasswordProtocol?
    
}

extension ResetPasswordPresenter : InteractorToPresenterResetPasswordProtocol {
    
 
}

