//
//  ResetPasswordViewController.swift
//  Capsula
//
//  Created SherifShokry on 1/4/20.
//  Copyright © 2020 SherifShokry. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class ResetPasswordViewController: UIViewController {
    
    var presenter : ViewToPresenterResetPasswordProtocol?

    
    override func viewDidLoad() {
        super.viewDidLoad()
       
    }
    
    
}
extension ResetPasswordViewController : PresenterToViewResetPasswordProtocol {
    

}
