//
//  ResetPasswordProtocols.swift
//  Capsula
//
//  Created SherifShokry on 1/4/20.
//  Copyright © 2020 SherifShokry. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation


protocol ViewToPresenterResetPasswordProtocol: class {
    
    var view : PresenterToViewResetPasswordProtocol? {get set}
    var interactor : PresenterToIntetractorResetPasswordProtocol? {get set}
    var router : PresenterToRouterResetPasswordProtocol? {get set}
}

protocol PresenterToViewResetPasswordProtocol: class {
  
}

protocol PresenterToIntetractorResetPasswordProtocol: class {
    var presenter: InteractorToPresenterResetPasswordProtocol? { get set }
    
}

protocol PresenterToRouterResetPasswordProtocol: class  {
    static func createModule() -> UIViewController
    
}

protocol InteractorToPresenterResetPasswordProtocol: class {
   
}
