//
//  RegisterPresenter.swift
//  Capsula
//
//  Created SherifShokry on 12/25/19.
//  Copyright © 2019 SherifShokry. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

class RegisterPresenter : ViewToPresenterRegisterProtocol{
    
    var view: PresenterToViewRegisterProtocol?
    var interactor: PresenterToIntetractorRegisterProtocol?
    var router: PresenterToRouterRegisterProtocol?
    
}

extension RegisterPresenter : InteractorToPresenterRegisterProtocol {
    
 
}

