//
//  RegisterViewController.swift
//  Capsula
//
//  Created SherifShokry on 12/25/19.
//  Copyright © 2019 SherifShokry. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class RegisterViewController: UIViewController {
    
    var presenter : ViewToPresenterRegisterProtocol?

    @IBOutlet weak var emailField : CapsulaInputFeild!
    @IBOutlet weak var phoneField : CapsulaInputFeild!
    @IBOutlet weak var passwordField : CapsulaInputFeild!
    @IBOutlet weak var nameField : CapsulaInputFeild!
    
    override func viewDidLoad() {
        super.viewDidLoad()
        
        setupInputFields()
    }
    
    
    func setupInputFields(){
        emailField.type = .email
        emailField.setTextFeildSpecs()
        phoneField.type = .phoneNumber
        phoneField.setTextFeildSpecs()
        passwordField.type = .password
        passwordField.setTextFeildSpecs()
        nameField.type = .name
        nameField.setTextFeildSpecs()
    }
    
    
    func validate() -> Bool {
        var isValid = true
        
        isValid = emailField.validate() && isValid
        isValid = nameField.validate() && isValid
        isValid = passwordField.validate() && isValid
        isValid = phoneField.validate() && isValid

        return isValid
    }
    
    
    
    @IBAction func registerPressed(_ sender : UIButton){
        
        
        if !validate() {
            return
        }
        
        
        
        
    }
    
    
    @IBAction func facebookPressed(_ sender : UIButton){
        
        
        
        
        
    }
 
    
    @IBAction func gmailPressed(_ sender : UIButton){
         
         
         
         
         
     }
     
    
    @IBAction func twitterPressed(_ sender : UIButton){
         
         
         
         
         
     }
     
    
    
}
extension RegisterViewController : PresenterToViewRegisterProtocol {
    

}
