//
//  RegisterProtocols.swift
//  Capsula
//
//  Created SherifShokry on 12/25/19.
//  Copyright © 2019 SherifShokry. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation


protocol ViewToPresenterRegisterProtocol: class {
    
    var view : PresenterToViewRegisterProtocol? {get set}
    var interactor : PresenterToIntetractorRegisterProtocol? {get set}
    var router : PresenterToRouterRegisterProtocol? {get set}
}

protocol PresenterToViewRegisterProtocol: class {
  
}

protocol PresenterToIntetractorRegisterProtocol: class {
    var presenter: InteractorToPresenterRegisterProtocol? { get set }
    
}

protocol PresenterToRouterRegisterProtocol: class  {
    static func createModule() -> UIViewController
    
}

protocol InteractorToPresenterRegisterProtocol: class {
   
}
