//
//  CompleteProfileInteractor.swift
//  Capsula
//
//  Created SherifShokry on 1/4/20.
//  Copyright © 2020 SherifShokry. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class CompleteProfileInteractor : PresenterToIntetractorCompleteProfileProtocol {
    
    var presenter: InteractorToPresenterCompleteProfileProtocol?
    
}

