//
//  CompleteProfilePresenter.swift
//  Capsula
//
//  Created SherifShokry on 1/4/20.
//  Copyright © 2020 SherifShokry. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

class CompleteProfilePresenter : ViewToPresenterCompleteProfileProtocol{
    
    var view: PresenterToViewCompleteProfileProtocol?
    var interactor: PresenterToIntetractorCompleteProfileProtocol?
    var router: PresenterToRouterCompleteProfileProtocol?
    
}

extension CompleteProfilePresenter : InteractorToPresenterCompleteProfileProtocol {
    
 
}

