//
//  CompleteProfileRouter.swift
//  Capsula
//
//  Created SherifShokry on 1/4/20.
//  Copyright © 2020 SherifShokry. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit


    class CompleteProfileRouter : PresenterToRouterCompleteProfileProtocol {
        
        static func createModule() -> UIViewController {
            
            let view = CompleteProfileViewController.instantiateFromStoryBoard(appStoryBoard: /*replace with storyboard name*/)
            let presenter : ViewToPresenterCompleteProfileProtocol & InteractorToPresenterCompleteProfileProtocol = CompleteProfilePresenter()
            let interactor : PresenterToIntetractorCompleteProfileProtocol = CompleteProfileInteractor()
            let router : PresenterToRouterCompleteProfileProtocol = CompleteProfileRouter()
            
            view.presenter = presenter
            presenter.interactor = interactor
            presenter.view = view
            presenter.router = router
            interactor.presenter = presenter
            return view
        }
    }
