//
//  CompleteProfileProtocols.swift
//  Capsula
//
//  Created SherifShokry on 1/4/20.
//  Copyright © 2020 SherifShokry. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation


protocol ViewToPresenterCompleteProfileProtocol: class {
    
    var view : PresenterToViewCompleteProfileProtocol? {get set}
    var interactor : PresenterToIntetractorCompleteProfileProtocol? {get set}
    var router : PresenterToRouterCompleteProfileProtocol? {get set}
}

protocol PresenterToViewCompleteProfileProtocol: class {
  
}

protocol PresenterToIntetractorCompleteProfileProtocol: class {
    var presenter: InteractorToPresenterCompleteProfileProtocol? { get set }
    
}

protocol PresenterToRouterCompleteProfileProtocol: class  {
    static func createModule() -> UIViewController
    
}

protocol InteractorToPresenterCompleteProfileProtocol: class {
   
}
