//
//  LogInInteractor.swift
//  Capsula
//
//  Created SherifShokry on 12/25/19.
//  Copyright © 2019 SherifShokry. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class LogInInteractor : PresenterToIntetractorLogInProtocol {
    
    var presenter: InteractorToPresenterLogInProtocol?
    
}

