//
//  LogInProtocols.swift
//  Capsula
//
//  Created SherifShokry on 12/25/19.
//  Copyright © 2019 SherifShokry. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation


protocol ViewToPresenterLogInProtocol: class {
    
    var view : PresenterToViewLogInProtocol? {get set}
    var interactor : PresenterToIntetractorLogInProtocol? {get set}
    var router : PresenterToRouterLogInProtocol? {get set}
}

protocol PresenterToViewLogInProtocol: class {
  
}

protocol PresenterToIntetractorLogInProtocol: class {
    var presenter: InteractorToPresenterLogInProtocol? { get set }
    
}

protocol PresenterToRouterLogInProtocol: class  {
    static func createModule() -> UIViewController
    
}

protocol InteractorToPresenterLogInProtocol: class {
   
}
