//
//  LogInViewController.swift
//  Capsula
//
//  Created SherifShokry on 12/25/19.
//  Copyright © 2019 SherifShokry. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class LogInViewController: UIViewController {
    
    var presenter : ViewToPresenterLogInProtocol?

    
    override func viewDidLoad() {
        super.viewDidLoad()
       
    }
    
    
}
extension LogInViewController : PresenterToViewLogInProtocol {
    

}
