//
//  LogInPresenter.swift
//  Capsula
//
//  Created SherifShokry on 12/25/19.
//  Copyright © 2019 SherifShokry. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

class LogInPresenter : ViewToPresenterLogInProtocol{
    
    var view: PresenterToViewLogInProtocol?
    var interactor: PresenterToIntetractorLogInProtocol?
    var router: PresenterToRouterLogInProtocol?
    
}

extension LogInPresenter : InteractorToPresenterLogInProtocol {
    
 
}

