//
//  LogInRouter.swift
//  Capsula
//
//  Created SherifShokry on 12/25/19.
//  Copyright © 2019 SherifShokry. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit


    class LogInRouter : PresenterToRouterLogInProtocol {
        
        static func createModule() -> UIViewController {
            
            let view = LogInViewController.instantiateFromStoryBoard(appStoryBoard: /*replace with storyboard name*/)
            let presenter : ViewToPresenterLogInProtocol & InteractorToPresenterLogInProtocol = LogInPresenter()
            let interactor : PresenterToIntetractorLogInProtocol = LogInInteractor()
            let router : PresenterToRouterLogInProtocol = LogInRouter()
            
            view.presenter = presenter
            presenter.interactor = interactor
            presenter.view = view
            presenter.router = router
            interactor.presenter = presenter
            return view
        }
    }
