//
//  MainRegisterPresenter.swift
//  Capsula
//
//  Created SherifShokry on 12/28/19.
//  Copyright © 2019 SherifShokry. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

class MainRegisterPresenter : ViewToPresenterMainRegisterProtocol{
    
    var view: PresenterToViewMainRegisterProtocol?
    var interactor: PresenterToIntetractorMainRegisterProtocol?
    var router: PresenterToRouterMainRegisterProtocol?
    
}

extension MainRegisterPresenter : InteractorToPresenterMainRegisterProtocol {
    
 
}

