//
//  MainRegisterRouter.swift
//  Capsula
//
//  Created SherifShokry on 12/28/19.
//  Copyright © 2019 SherifShokry. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit


    class MainRegisterRouter : PresenterToRouterMainRegisterProtocol {
        
        static func createModule() -> UIViewController {
            
            let view = MainRegisterViewController.instantiateFromStoryBoard(appStoryBoard: /*replace with storyboard name*/)
            let presenter : ViewToPresenterMainRegisterProtocol & InteractorToPresenterMainRegisterProtocol = MainRegisterPresenter()
            let interactor : PresenterToIntetractorMainRegisterProtocol = MainRegisterInteractor()
            let router : PresenterToRouterMainRegisterProtocol = MainRegisterRouter()
            
            view.presenter = presenter
            presenter.interactor = interactor
            presenter.view = view
            presenter.router = router
            interactor.presenter = presenter
            return view
        }
    }
