//
//  MainRegisterViewController.swift
//  Capsula
//
//  Created SherifShokry on 12/28/19.
//  Copyright © 2019 SherifShokry. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class MainRegisterViewController: UIViewController {
    
    var presenter : ViewToPresenterMainRegisterProtocol?

    
    override func viewDidLoad() {
        super.viewDidLoad()
       
    }
    
    
}
extension MainRegisterViewController : PresenterToViewMainRegisterProtocol {
    

}
