//
//  MainRegisterInteractor.swift
//  Capsula
//
//  Created SherifShokry on 12/28/19.
//  Copyright © 2019 SherifShokry. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class MainRegisterInteractor : PresenterToIntetractorMainRegisterProtocol {
    
    var presenter: InteractorToPresenterMainRegisterProtocol?
    
}

