//
//  MainRegisterProtocols.swift
//  Capsula
//
//  Created SherifShokry on 12/28/19.
//  Copyright © 2019 SherifShokry. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation


protocol ViewToPresenterMainRegisterProtocol: class {
    
    var view : PresenterToViewMainRegisterProtocol? {get set}
    var interactor : PresenterToIntetractorMainRegisterProtocol? {get set}
    var router : PresenterToRouterMainRegisterProtocol? {get set}
}

protocol PresenterToViewMainRegisterProtocol: class {
  
}

protocol PresenterToIntetractorMainRegisterProtocol: class {
    var presenter: InteractorToPresenterMainRegisterProtocol? { get set }
    
}

protocol PresenterToRouterMainRegisterProtocol: class  {
    static func createModule() -> UIViewController
    
}

protocol InteractorToPresenterMainRegisterProtocol: class {
   
}
