//
//  CategoriesListViewController.swift
//  Capsula
//
//  Created SherifShokry on 2/7/20.
//  Copyright © 2020 SherifShokry. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class CategoriesListViewController: UIViewController {
    
    var presenter : ViewToPresenterCategoriesListProtocol?

    
    override func viewDidLoad() {
        super.viewDidLoad()
       
    }
    
    
}
extension CategoriesListViewController : PresenterToViewCategoriesListProtocol {
    

}
