//
//  CategoriesListPresenter.swift
//  Capsula
//
//  Created SherifShokry on 2/7/20.
//  Copyright © 2020 SherifShokry. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

class CategoriesListPresenter : ViewToPresenterCategoriesListProtocol{
    
    var view: PresenterToViewCategoriesListProtocol?
    var interactor: PresenterToIntetractorCategoriesListProtocol?
    var router: PresenterToRouterCategoriesListProtocol?
    
}

extension CategoriesListPresenter : InteractorToPresenterCategoriesListProtocol {
    
 
}

