//
//  CategoriesListRouter.swift
//  Capsula
//
//  Created SherifShokry on 2/7/20.
//  Copyright © 2020 SherifShokry. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit


    class CategoriesListRouter : PresenterToRouterCategoriesListProtocol {
        
        static func createModule() -> UIViewController {
            
            let view = CategoriesListViewController.instantiateFromStoryBoard(appStoryBoard: /*replace with storyboard name*/)
            let presenter : ViewToPresenterCategoriesListProtocol & InteractorToPresenterCategoriesListProtocol = CategoriesListPresenter()
            let interactor : PresenterToIntetractorCategoriesListProtocol = CategoriesListInteractor()
            let router : PresenterToRouterCategoriesListProtocol = CategoriesListRouter()
            
            view.presenter = presenter
            presenter.interactor = interactor
            presenter.view = view
            presenter.router = router
            interactor.presenter = presenter
            return view
        }
    }
