//
//  CategoriesListInteractor.swift
//  Capsula
//
//  Created SherifShokry on 2/7/20.
//  Copyright © 2020 SherifShokry. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class CategoriesListInteractor : PresenterToIntetractorCategoriesListProtocol {
    
    var presenter: InteractorToPresenterCategoriesListProtocol?
    
}

