//
//  CategoriesListProtocols.swift
//  Capsula
//
//  Created SherifShokry on 2/7/20.
//  Copyright © 2020 SherifShokry. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation


protocol ViewToPresenterCategoriesListProtocol: class {
    
    var view : PresenterToViewCategoriesListProtocol? {get set}
    var interactor : PresenterToIntetractorCategoriesListProtocol? {get set}
    var router : PresenterToRouterCategoriesListProtocol? {get set}
}

protocol PresenterToViewCategoriesListProtocol: class {
  
}

protocol PresenterToIntetractorCategoriesListProtocol: class {
    var presenter: InteractorToPresenterCategoriesListProtocol? { get set }
    
}

protocol PresenterToRouterCategoriesListProtocol: class  {
    static func createModule() -> UIViewController
    
}

protocol InteractorToPresenterCategoriesListProtocol: class {
   
}
