//
//  StoresListProtocols.swift
//  Capsula
//
//  Created SherifShokry on 2/7/20.
//  Copyright © 2020 SherifShokry. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation


protocol ViewToPresenterStoresListProtocol: class {
    
    var view : PresenterToViewStoresListProtocol? {get set}
    var interactor : PresenterToIntetractorStoresListProtocol? {get set}
    var router : PresenterToRouterStoresListProtocol? {get set}
}

protocol PresenterToViewStoresListProtocol: class {
  
}

protocol PresenterToIntetractorStoresListProtocol: class {
    var presenter: InteractorToPresenterStoresListProtocol? { get set }
    
}

protocol PresenterToRouterStoresListProtocol: class  {
    static func createModule() -> UIViewController
    
}

protocol InteractorToPresenterStoresListProtocol: class {
   
}
