//
//  StoresListViewController.swift
//  Capsula
//
//  Created SherifShokry on 2/7/20.
//  Copyright © 2020 SherifShokry. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class StoresListViewController: UIViewController {
    
    var presenter : ViewToPresenterStoresListProtocol?

    
    override func viewDidLoad() {
        super.viewDidLoad()
       
    }
    
    
}
extension StoresListViewController : PresenterToViewStoresListProtocol {
    

}
