//
//  StoresListPresenter.swift
//  Capsula
//
//  Created SherifShokry on 2/7/20.
//  Copyright © 2020 SherifShokry. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

class StoresListPresenter : ViewToPresenterStoresListProtocol{
    
    var view: PresenterToViewStoresListProtocol?
    var interactor: PresenterToIntetractorStoresListProtocol?
    var router: PresenterToRouterStoresListProtocol?
    
}

extension StoresListPresenter : InteractorToPresenterStoresListProtocol {
    
 
}

