//
//  ItemDetailsProtocols.swift
//  Capsula
//
//  Created SherifShokry on 3/28/20.
//  Copyright © 2020 SherifShokry. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation


protocol ViewToPresenterItemDetailsProtocol: class {
    
    var view : PresenterToViewItemDetailsProtocol? {get set}
    var interactor : PresenterToIntetractorItemDetailsProtocol? {get set}
    var router : PresenterToRouterItemDetailsProtocol? {get set}
}

protocol PresenterToViewItemDetailsProtocol: class {
  
}

protocol PresenterToIntetractorItemDetailsProtocol: class {
    var presenter: InteractorToPresenterItemDetailsProtocol? { get set }
    
}

protocol PresenterToRouterItemDetailsProtocol: class  {
    static func createModule() -> UIViewController
    
}

protocol InteractorToPresenterItemDetailsProtocol: class {
   
}
