//
//  ItemDetailsInteractor.swift
//  Capsula
//
//  Created SherifShokry on 3/28/20.
//  Copyright © 2020 SherifShokry. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class ItemDetailsInteractor : PresenterToIntetractorItemDetailsProtocol {
    
    var presenter: InteractorToPresenterItemDetailsProtocol?
    
}

