//
//  ItemDetailsRouter.swift
//  Capsula
//
//  Created SherifShokry on 3/28/20.
//  Copyright © 2020 SherifShokry. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit


    class ItemDetailsRouter : PresenterToRouterItemDetailsProtocol {
        
        static func createModule() -> UIViewController {
            
            let view = ItemDetailsViewController.instantiateFromStoryBoard(appStoryBoard: /*replace with storyboard name*/)
            let presenter : ViewToPresenterItemDetailsProtocol & InteractorToPresenterItemDetailsProtocol = ItemDetailsPresenter()
            let interactor : PresenterToIntetractorItemDetailsProtocol = ItemDetailsInteractor()
            let router : PresenterToRouterItemDetailsProtocol = ItemDetailsRouter()
            
            view.presenter = presenter
            presenter.interactor = interactor
            presenter.view = view
            presenter.router = router
            interactor.presenter = presenter
            return view
        }
    }
