//
//  ItemDetailsViewController.swift
//  Capsula
//
//  Created SherifShokry on 3/28/20.
//  Copyright © 2020 SherifShokry. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class ItemDetailsViewController: UIViewController {
    
    var presenter : ViewToPresenterItemDetailsProtocol?

    
    override func viewDidLoad() {
        super.viewDidLoad()
       
    }
    
    
}
extension ItemDetailsViewController : PresenterToViewItemDetailsProtocol {
    

}
