//
//  ForgetPasswordPresenter.swift
//  Capsula
//
//  Created SherifShokry on 12/25/19.
//  Copyright © 2019 SherifShokry. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

class ForgetPasswordPresenter : ViewToPresenterForgetPasswordProtocol{
    
    var view: PresenterToViewForgetPasswordProtocol?
    var interactor: PresenterToIntetractorForgetPasswordProtocol?
    var router: PresenterToRouterForgetPasswordProtocol?
    
}

extension ForgetPasswordPresenter : InteractorToPresenterForgetPasswordProtocol {
    
 
}

