//
//  ForgetPasswordProtocols.swift
//  Capsula
//
//  Created SherifShokry on 12/25/19.
//  Copyright © 2019 SherifShokry. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation
import UIKit


protocol ViewToPresenterForgetPasswordProtocol: class {
    
    var view : PresenterToViewForgetPasswordProtocol? {get set}
    var interactor : PresenterToIntetractorForgetPasswordProtocol? {get set}
    var router : PresenterToRouterForgetPasswordProtocol? {get set}
}

protocol PresenterToViewForgetPasswordProtocol: class {
  
}

protocol PresenterToIntetractorForgetPasswordProtocol: class {
    var presenter: InteractorToPresenterForgetPasswordProtocol? { get set }
    
}

protocol PresenterToRouterForgetPasswordProtocol: class  {
    static func createModule() -> UIViewController
    
}

protocol InteractorToPresenterForgetPasswordProtocol: class {
   
}
