//
//  ForgetPasswordViewController.swift
//  Capsula
//
//  Created SherifShokry on 12/25/19.
//  Copyright © 2019 SherifShokry. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class ForgetPasswordViewController: UIViewController {
    
    var presenter : ViewToPresenterForgetPasswordProtocol?
    @IBOutlet weak var phoneField : CapsulaInputFeild!
    @IBOutlet weak var containerView : UIView!
    override func viewDidLoad() {
        super.viewDidLoad()
       setupInputField()
    }
    
    override func viewWillLayoutSubviews() {
          super.viewWillLayoutSubviews()
          containerView.clipsToBounds = true
          containerView.layer.cornerRadius = 70
          containerView.layer.maskedCorners = [.layerMaxXMinYCorner]
      }
      
    
    func  setupInputField() {
        phoneField.type = .phoneNumber
        phoneField.setTextFeildSpecs()
     }
   
    func validate() -> Bool {
           var isValid = true
           isValid = phoneField.validate() && isValid
           return isValid
    }
     
    
    
    @IBAction func forgetPassword(_ sender : UIButton){
        
        if !validate(){
            return
        }
        
        //
        
    }
    
    
    
    
    
}
extension ForgetPasswordViewController : PresenterToViewForgetPasswordProtocol {
    

}
